"""Initial migration

Revision ID: 73cb5a02788c
Revises: 
Create Date: 2024-05-05 20:49:11.697964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cb5a02788c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comment',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('post_id', sa.Integer(), sa.ForeignKey('post.id'), nullable=False),
    )

    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])

    # Убираем создание внешнего ключа в таблице post
    # op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])

    # Не добавляем user_id в post, так как он уже был добавлен

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # Удаляем таблицу comment
    op.drop_table('comment')
    # ### end Alembic commands ###
